# procesos que ha de fer la shiny
# Generated by OmopViewer 0.7.0
# Be careful editing this file

server <- function(input, output, session) {
  # summary ----
  output$summary_cdm_name <- shinyTree::renderTree(summaryCdmName(data))
  output$summary_packages <- shinyTree::renderTree(summaryPackages(data))
  output$summary_min_cell_count <- shinyTree::renderTree(summaryMinCellCount(data))
  output$summary_panels <- shinyTree::renderTree(summaryPanels(data))
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      data |>
        omopgenerics::bind() |>
        omopgenerics::exportSummarisedResult(
          fileName = file, logFile = NULL, logSqlPath = NULL
        )
    }
  )
  # update buttons ----
  updateButtons <- shiny::reactiveValues(
    summarise_omop_snapshot = FALSE,
    summarise_observation_period = FALSE,
    summarise_cohort_attrition = FALSE,
    summarise_characteristics = FALSE,
    summarise_log_file = FALSE,
    summarise_table = FALSE,
    vaccinated_table = FALSE,
    summarise_coverage = FALSE
  )


  # summarise_omop_snapshot -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_omop_snapshot <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_omop_snapshot_cdm_name,
      input$summarise_omop_snapshot_variable_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_omop_snapshot, {
    if (updateButtons$summarise_omop_snapshot == TRUE) {
      output$update_message_summarise_omop_snapshot <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_omop_snapshot <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_omop_snapshot, {
    updateButtons$summarise_omop_snapshot <- FALSE
  })

  ## get summarise_omop_snapshot data
  getSummariseOmopSnapshotData <- shiny::eventReactive(input$update_summarise_omop_snapshot, {
    data[["summarise_omop_snapshot"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_omop_snapshot_cdm_name,
        .data$variable_name %in% input$summarise_omop_snapshot_variable_name
      )
  })
  getSummariseOmopSnapshotTable <- shiny::reactive({
    getSummariseOmopSnapshotData() |>
      OmopSketch::tableOmopSnapshot(
        header = input$summarise_omop_snapshot_table_header,
        groupColumn = input$summarise_omop_snapshot_table_group_column,
        hide = input$summarise_omop_snapshot_table_hide
      )
  })
  output$summarise_omop_snapshot_table <- gt::render_gt({
    getSummariseOmopSnapshotTable()
  })
  output$summarise_omop_snapshot_table_download <- shiny::downloadHandler(
    filename = paste0("table_snapshot.", input$summarise_omop_snapshot_table_format),
    content = function(file) {
      gt::gtsave(getSummariseOmopSnapshotTable(), file)
    }
  )

  # summarise_observation_period -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_observation_period <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_observation_period_cdm_name,
      input$summarise_observation_period_observation_period_ordinal,
      input$summarise_observation_period_variable_name,
      input$summarise_observation_period_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_observation_period, {
    if (updateButtons$summarise_observation_period == TRUE) {
      output$update_message_summarise_observation_period <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_observation_period <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_observation_period, {
    updateButtons$summarise_observation_period <- FALSE
  })

  ## get summarise_observation_period data
  getSummariseObservationPeriodData <- shiny::eventReactive(input$update_summarise_observation_period, {
    data[["summarise_observation_period"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_observation_period_cdm_name,
        .data$variable_name %in% input$summarise_observation_period_variable_name,
        .data$estimate_name %in% input$summarise_observation_period_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$observation_period_ordinal %in% input$summarise_observation_period_observation_period_ordinal)
  })
  getSummariseObservationPeriodTable <- shiny::reactive({
    getSummariseObservationPeriodData() |>
      OmopSketch::tableObservationPeriod(
        header = input$summarise_observation_period_table_header,
        groupColumn = input$summarise_observation_period_table_group_column,
        hide = input$summarise_observation_period_table_hide
      )
  })
  output$summarise_observation_period_table <- gt::render_gt({
    getSummariseObservationPeriodTable()
  })
  output$summarise_observation_period_table_download <- shiny::downloadHandler(
    filename = paste0("table_obsevation_period.", input$summarise_observation_period_table_format),
    content = function(file) {
      gt::gtsave(getSummariseObservationPeriodTable(), file)
    }
  )
  getSummariseObservationPeriodPlot <- shiny::reactive({
    getSummariseObservationPeriodData() |>
      OmopSketch::plotObservationPeriod(
        variableName = input$summarise_observation_period_plot_variable,
        plotType = input$summarise_observation_period_plot_plot_type,
        facet = input$summarise_observation_period_plot_facet,
        colour = input$summarise_observation_period_plot_colour
      )
  })
  output$summarise_observation_period_plot <- shiny::renderUI({
    x <- getSummariseObservationPeriodPlot()
    renderInteractivePlot(x, input$summarise_observation_period_plot_interactive)
  })
  output$summarise_observation_period_plot_download <- shiny::downloadHandler(
    filename = "plot_observation_period.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseObservationPeriodPlot(),
        width = as.numeric(input$summarise_observation_period_plot_width),
        height = as.numeric(input$summarise_observation_period_plot_height),
        units = input$summarise_observation_period_plot_units,
        dpi = as.numeric(input$summarise_observation_period_plot_dpi)
      )
    }
  )

  # summarise_cohort_attrition -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_cohort_attrition <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_cohort_attrition_cdm_name,
      input$summarise_cohort_attrition_cohort_name,
      input$summarise_cohort_attrition_table_name,
      input$summarise_cohort_attrition_variable_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_cohort_attrition, {
    if (updateButtons$summarise_cohort_attrition == TRUE) {
      output$update_message_summarise_cohort_attrition <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_cohort_attrition <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_cohort_attrition, {
    updateButtons$summarise_cohort_attrition <- FALSE
  })

  ## get summarise_cohort_attrition data
    getSummariseCohortAttritionData <- shiny::eventReactive(input$update_summarise_cohort_attrition, {
      data[["summarise_cohort_attrition"]] |>
        dplyr::filter(
          .data$cdm_name %in% input$summarise_cohort_attrition_cdm_name,
          .data$variable_name %in% input$summarise_cohort_attrition_variable_name
        ) |>
        dplyr::mutate(
          group_level = pretty_labels(group_level),
          group_level = factor(
            group_level,
            levels = c("Covid vaccine", "Autumn 2023", "Spring 2024", "Autumn 2024", "Spring 2025")
          )) |>
        print()|>
        omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_cohort_attrition_cohort_name) |>
        omopgenerics::filterSettings(.data$table_name %in% input$summarise_cohort_attrition_table_name) 
       
    })
  getSummariseCohortAttritionTable <- shiny::reactive({
    getSummariseCohortAttritionData() |>
      dplyr::arrange(.data$group_level) |>
      CohortCharacteristics::tableCohortAttrition(
        header = input$summarise_cohort_attrition_table_header,
        groupColumn = input$summarise_cohort_attrition_table_group_column,
        hide = input$summarise_cohort_attrition_table_hide
      )
  })
  output$summarise_cohort_attrition_table <- gt::render_gt({
    getSummariseCohortAttritionTable()
  })
  output$summarise_cohort_attrition_table_download <- shiny::downloadHandler(
    filename = paste0("table_attrition.", input$summarise_cohort_attrition_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCohortAttritionTable(), file)
    }
  )
  getSummariseCohortAttritionDiagram <- shiny::reactive({
    getSummariseCohortAttritionData() |>
      dplyr::arrange(.data$group_level) |>
      CohortCharacteristics::plotCohortAttrition(
        show = input$summarise_cohort_attrition_diagram_show
      )
  })
  output$summarise_cohort_attrition_diagram <- DiagrammeR::renderGrViz({
    getSummariseCohortAttritionDiagram()
  })
  output$summarise_cohort_attrition_diagram_download <- shiny::downloadHandler(
    filename = "attrition_diagram.png",
    content = function(file) {
      svg <- DiagrammeRsvg::export_svg(getSummariseCohortAttritionDiagram())
      rsvg::rsvg_png(charToRaw(svg), file, width = input$summarise_cohort_attrition_diagram_width)
    }
  )

  # summarise_characteristics -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_characteristics <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_characteristics_cdm_name,
      input$summarise_characteristics_cohort_name,
      input$summarise_characteristics_table_name,
      input$summarise_characteristics_variable_name,
      input$summarise_characteristics_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_characteristics, {
    if (updateButtons$summarise_characteristics == TRUE) {
      output$update_message_summarise_characteristics <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_characteristics <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_characteristics, {
    updateButtons$summarise_characteristics <- FALSE
  })

  ## get summarise_characteristics data
  getSummariseCharacteristicsData <- shiny::eventReactive(input$update_summarise_characteristics, {
    data[["summarise_characteristics"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_characteristics_cdm_name,
        .data$variable_name %in% input$summarise_characteristics_variable_name,
        .data$estimate_name %in% input$summarise_characteristics_estimate_name
      ) |>
      print()|>
      dplyr::mutate(
        variable_name = case_when(variable_name == "Imd" ~ "TDI",
                                  TRUE ~ variable_name),
        group_level = pretty_labels(group_level)) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_characteristics_cohort_name) |>
      omopgenerics::filterSettings(.data$table_name %in% input$summarise_characteristics_table_name)
  })
  getSummariseCharacteristicsTable <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::tableCharacteristics(
        header = input$summarise_characteristics_table_header,
        groupColumn = input$summarise_characteristics_table_group_column,
        hide = input$summarise_characteristics_table_hide
      )
  })
  output$summarise_characteristics_table <- gt::render_gt({
    getSummariseCharacteristicsTable()
  })
  output$summarise_characteristics_table_download <- shiny::downloadHandler(
    filename = paste0("table_characteristics.", input$summarise_characteristics_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCharacteristicsTable(), file)
    }
  )
  getSummariseCharacteristicsPlot <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::plotCharacteristics(
        plotType = input$summarise_characteristics_plot_plot_type,
        facet = input$summarise_characteristics_plot_facet,
        colour = input$summarise_characteristics_plot_colour
      )
  })
  
  output$summarise_characteristics_plot <- shiny::renderUI({
    x <- getSummariseCharacteristicsPlot()
    renderInteractivePlot(x, input$summarise_characteristics_plot_interactive)
  })
  output$summarise_characteristics_plot_download <- shiny::downloadHandler(
    filename = "plot_characteristics.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseCharacteristicsPlot(),
        width = as.numeric(input$summarise_characteristics_plot_width),
        height = as.numeric(input$summarise_characteristics_plot_height),
        units = input$summarise_characteristics_plot_units,
        dpi = as.numeric(input$summarise_characteristics_plot_dpi)
      )
    }
  )

  # Vaccination Chronology -----
  ## vaccinated eligibles in campaign, imported by me 
  library(dplyr)
  library(readr)
  library(ggplot2)
  
  plot_dose <- read.csv(here::here("plot_dose.csv"))
  
  plot_dose <- plot_dose |>
    mutate(cohort_start_date = as.Date(cohort_start_date))
  
  plot_dosef <- plot_dose |> filter(n_dose_day>5L)
  
  campaigns <- tibble::tibble(
    vaccination_campaign = c("a_2023","s_2024","a_2024","s_2025","a_2025"),
    start    = as.Date(c("2023-10-02","2024-04-15","2024-10-03","2025-04-01","2025-10-01")), 
    end      = as.Date(c("2024-01-31","2024-06-30","2025-01-31","2025-06-17","2026-01-31"))
  ) |>
    mutate(
      split = case_when(
        vaccination_campaign == "a_2023" ~ end - 47,
        vaccination_campaign == "a_2024" ~ end - 42,
        vaccination_campaign == "a_2025" ~ end - 45,
        TRUE ~ as.Date(NA)
      )
    )|>
    filter(!vaccination_campaign=="a_2025")
  
  bg_full <- campaigns |>
    transmute(
      vaccination_campaign,
      xmin = start,
      xmax = end,
      ymin = -Inf,
      ymax = Inf
    )
  
  bg_tail <- campaigns |>
    filter(!is.na(split)) |>
    transmute(
      vaccination_campaign,
      xmin = split,
      xmax = end,
      ymin = -Inf,
      ymax = Inf
    )
  
  plot_dosef <- plot_dosef |>
    mutate(
      Dose = factor(
        paste(dose, "dose"),
        levels = paste(1:13, "dose"),
        ordered = TRUE
      )
    )|>
    collect(name=plot_dosef) 
  
  y_max <- max(plot_dosef$n_dose_day, na.rm = TRUE) * 1.05
  
  bg_full <- campaigns |>
    transmute(vaccination_campaign, xmin = start, xmax = end, ymin = 0, ymax = y_max)
  
  bg_tail <- campaigns |>
    filter(!is.na(split)) |>
    transmute(vaccination_campaign, xmin = split, xmax = end, ymin = 0, ymax = y_max)
  graph <- ggplot(plot_dosef|>filter(!vaccination_campaign == "a_2025"), aes(x = cohort_start_date, y = n_dose_day, fill = Dose)) +
    geom_rect(
      data = bg_full,
      aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
      inherit.aes = FALSE,
      fill = "grey90",
      alpha = 0.5
    ) +
    geom_rect(
      data = bg_tail,
      aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
      inherit.aes = FALSE,
      fill = "grey75",
      alpha = 0.6
    ) +
    geom_col(position = "stack", width = 1) +
    scale_x_date(date_breaks = "3 month", 
                 limits = c(as.Date("2020-12-01"), NA),
                 date_labels = "%Y-%m", expand = c(0, 0)) +
    theme_bw() +
    theme(legend.position = "bottom", axis.text.x = element_text(angle = 45, hjust = 1)) +
    labs(x = "Date", y = "Number of vaccine recipients")
  print(graph) 

  ac <- plot_dosef |> group_by(Dose) |>
    mutate(
      acummulative_vaccination = cumsum(n_dose_day)
    ) |>
    ungroup() 
  y_max <- max(ac$acummulative_vaccination, na.rm = TRUE) * 1.05
  
  bg_full <- campaigns |>
    transmute(vaccination_campaign, xmin = start, xmax = end, ymin = 0, ymax = y_max)
  
  bg_tail <- campaigns |>
    filter(!is.na(split)) |>
    transmute(vaccination_campaign, xmin = split, xmax = end, ymin = 0, ymax = y_max)
  plot0 <- ggplot(ac, aes(x = cohort_start_date, y = acummulative_vaccination, colour = Dose)) +
    geom_rect(
      data = bg_full,
      aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
      inherit.aes = FALSE,
      fill = "grey90",
      alpha = 0.5
    ) +
    geom_rect(
      data = bg_tail,
      aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
      inherit.aes = FALSE,
      fill = "grey75",
      alpha = 0.6
    ) +
    geom_line(linewidth = 1) +
    scale_x_date(
      date_breaks = "3 month",
      limits = c(as.Date("2020-12-01"), NA),
      date_labels = "%Y-%m",
      expand = c(0, 0)
    ) +
    scale_y_continuous(
      expand = expansion(mult = c(0, 0.05)),
      breaks = scales::pretty_breaks(n = 5),
      labels = scales::label_number(big.mark = ",")
    ) +
    theme_bw() +
    theme(
      legend.position = "bottom",
      axis.text.x = element_text(angle = 45, hjust = 1),
      axis.text.y = element_text(margin = margin(r = 6)),
      axis.title.y = element_text(margin = margin(r = 10)),
      plot.margin = margin(10, 30, 10, 20)
    ) +
    guides(colour = guide_legend(nrow = 2)) +
    labs(
      x = "Date",
      y = "Cumulative number of vaccine recipients",
      colour = "Dose:"
    )
  
  library(dplyr)
  library(readr)
  library(ggplot2)
  
  plot_dose <- read.csv(here::here("plot_dosee.csv"))
  
  plot_dose <- plot_dose |>
    mutate(cohort_start_date = as.Date(cohort_start_date))
  
  plot_dosef <- plot_dose |> filter(n_dose_day>5L)
  
  campaigns <- tibble::tibble(
    vaccination_campaign = c("a_2023","s_2024","a_2024","s_2025","a_2025"),
    start    = as.Date(c("2023-10-02","2024-04-15","2024-10-03","2025-04-01","2025-10-01")), 
    end      = as.Date(c("2024-01-31","2024-06-30","2025-01-31","2025-06-17","2026-01-31"))
  ) |>
    mutate(
      split = case_when(
        vaccination_campaign == "a_2023" ~ end - 47,
        vaccination_campaign == "a_2024" ~ end - 42,
        vaccination_campaign == "a_2025" ~ end - 45,
        TRUE ~ as.Date(NA)
      )
    )
  
  plot_dosef <- plot_dosef |>
    mutate(
      Dose = factor(
        paste(dose, "dose"),
        levels = paste(3: 12, "dose"),
        ordered = TRUE
      )
    )|>
    collect(name=plot_dosef) 
  
  plot_with_campaign <- plot_dosef |>
    filter(vaccination_campaign!="None" & !is.na(vaccination_campaign))
  
  plot_with_campaign <- plot_with_campaign |>
    left_join(campaigns, by = "vaccination_campaign") |>
    mutate(day_campaign = cohort_start_date - start) |>
    mutate(vaccination_campaign = factor(vaccination_campaign,
                                         levels = c("a_2023", "s_2024", "a_2024", "s_2025"), 
                                         labels = c("Autumn 2023", "Spring 2024",
                                                    "Autumn 2024", "Spring 2025"),
                                         ordered = TRUE))
  
  campaign_bands <- campaigns |>
    mutate(
      x_end = as.numeric(end - start),
      x_split = case_when(
        vaccination_campaign == "a_2023" ~ x_end - 47,
        vaccination_campaign == "a_2024" ~ x_end - 42,
        vaccination_campaign == "a_2025" ~ x_end - 45,
        TRUE ~ NA_real_
      )
    )|>
    mutate(vaccination_campaign = factor(vaccination_campaign,
                                         levels = c("a_2023", "s_2024", "a_2024", "s_2025"), 
                                         labels = c("Autumn 2023", "Spring 2024",
                                                    "Autumn 2024", "Spring 2025"),
                                         ordered = TRUE)) |>
    filter(!is.na(vaccination_campaign))
  
  bg_full <- campaign_bands |>
    transmute( #mutate(.keep = "none")
      vaccination_campaign,
      xmin = 0,
      xmax = x_end,
      ymin = -Inf,
      ymax = Inf
    )
  
  bg_tail <- campaign_bands |>
    filter(!is.na(x_split)) |>
    transmute(
      vaccination_campaign,
      xmin = x_split,
      xmax = x_end,
      ymin = -Inf,
      ymax = Inf
    )
  
  graph2 <- ggplot(
    plot_with_campaign |>
      filter(!is.na(vaccination_campaign)) |>
      mutate(day_campaign = as.numeric(day_campaign)),
    aes(x = day_campaign, y = n_dose_day, fill = Dose)
  ) +
    geom_rect(
      data = bg_full,
      aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
      inherit.aes = FALSE,
      fill = "grey90",
      alpha = 0.5
    ) +
    geom_rect(
      data = bg_tail,
      aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax),
      inherit.aes = FALSE,
      fill = "grey75",
      alpha = 0.6
    ) +
    geom_col() +
    facet_grid(vaccination_campaign ~ ., scales = "free_x", space = "free_x") +
    scale_x_continuous(expand = c(0, 0)) +
    theme_bw() +
    theme(axis.title = element_text(size = 20),      # x and y axis titles
          axis.text = element_text(size = 14),       # axis tick labels
          legend.title = element_text(size = 16),    # legend title
          legend.text = element_text(size = 14),     # legend labels
          plot.title = element_text(size = 18),      # plot title
          strip.text = element_text(size = 14)       # facet labels
    ) +
    labs(x = "Days since campaign start", y = "Number of vaccine recipients")
  
  print(graph2)
  
  output$eligibles_plot1 <- shiny::renderUI({
    x <- graph
    renderInteractivePlot(x, TRUE)
  })
  
  output$eligibles_plot <- shiny::renderUI({
    x <- graph2
    renderInteractivePlot(x, TRUE)
  })
  
  output$cumulative_eligibles_plot <- shiny::renderUI({
    x <- plot0
    renderInteractivePlot(x, TRUE)
  })
  
  output$summarise_choronology_plot_download1 <- shiny::downloadHandler(
    filename = function() {
      "vaccinated_all1.png"
    },
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = graph,
        width = 15,
        height = 15,
        units = "cm",
        dpi = 300
      )
    }
  )
  
  output$summarise_choronology_plot_download <- shiny::downloadHandler(
    filename = function() {
      "EligiblesVaccinatedInCampaign1.png"
    },
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = graph2,
        width = 15,
        height = 15,
        units = "cm",
        dpi = 300
      )
    }
  )
  
  output$summarise_choronology_plot_download3 <- shiny::downloadHandler(
    filename = function() {
      "CumulativeVaccinationChronologyOverall.png"
    },
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = plot0,
        width = 15,
        height = 15,
        units = "cm",
        dpi = 300
      )
    }
  )
  # vaccinated_table (Strata)-----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$vaccinated_table <- TRUE
  }) |>
    shiny::bindEvent(
      input$vaccinated_table_cdm_name,
      input$vaccinated_table_cohort_name,
      input$vaccinated_table_plot_strata_columns,
      ignoreInit = TRUE
    )
  
  shiny::observeEvent(updateButtons$vaccinated_table, {
    if (updateButtons$vaccinated_table == TRUE) {
      output$update_message_svaccinated_table <- shiny::renderUI(updateMessage)
    } else {
      output$update_message_vaccinated_table <- shiny::renderUI(NULL)
    }
  })
  
  shiny::observeEvent(input$update_vaccinated_table, {
    updateButtons$vaccinated_table <- FALSE
  })
  plot_levels <- c("England", "Northern Ireland", "Scotland", "Wales", 
                   "Q1(least deprived)", "Q2", "Q3", "Q4", "Q5(most deprived)",
                   "White", "Black", "Asian", "Unknown",
                   "Female", "Male", as.character(2:11),
                   "No", "Yes", "<=34", "35-44", "45-54", "55-64",
                   "65-74", "75-84", "85-94", ">=95", "Overall")
  getVaccinatedTableData <- shiny::eventReactive(input$update_vaccinated_table, {
    data[["vaccinated_table"]] |>
      dplyr::filter(
        .data$variable_name == "vaccinated",
        .data$estimate_name == "count"
      ) |>
      dplyr::filter(
        .data$cdm_name %in% input$vaccinated_table_cdm_name) |>
      print()|>
      mutate(group_level = dplyr::recode(
        .data$group_level,
        a_2023 = "Autumn 2023",
        s_2024 = "Spring 2024",
        a_2024 = "Autumn 2024",
        s_2025 = "Spring 2025"
      ),
      strata_name = dplyr::recode(
        .data$strata_name,
        ethnicity = "Ethnicity",
        sex = "Sex",
        prior_dose = "Prior dose",
        imd = "TDI",
        age_eligibility = "Age eligibility",
        immunosuppressed = "Immunosuppressed",
        age_group = "Age group",
        overall = "Overall",
        region = "Region"))|>
      print()|>
      mutate(group_level = factor(
        .data$group_level,
        levels = c("Autumn 2023", "Spring 2024", "Autumn 2024", "Spring 2025")),
        #estimate_value = as.numeric(.data$estimate_value),
        strata_level = dplyr::recode(
          .data$strata_level, 
          Q1 = "Q1(least deprived)",
          Q5 = "Q5(most deprived)",
          `0` = "No",
          `1` = "Yes",
          missing = "Unknown",
          asian = "Asian",
          black = "Black",
          white = "White",
          overall = "Overall"))|>
      print()|>
      omopgenerics::filterGroup(.data$cohort_name %in% input$vaccinated_table_cohort_name) |>
      filter(.data$strata_name %in% input$vaccinated_table_plot_strata_columns) |>
      print()
  })
  
  
  ## get coverage plots
  getVaccinatedTablePlot <- shiny::reactive({
    
    df <- getVaccinatedTableData() |>
      print()|>
      #mutate(strata_level=if_else(is.na(.data$strata_level), "Overall", 
      #                                  .data$strata_level)) |>
      dplyr::mutate(estimate_value = as.numeric(.data$estimate_value)) |>
      dplyr::filter(!is.na(.data$estimate_value))
    
    ggplot2::ggplot(
      df,
      ggplot2::aes(x = .data$estimate_value, y = .data$strata_level, fill = .data$strata_name)
    ) +
      ggplot2::geom_col(show.legend = FALSE) +
      ggplot2::facet_grid(
        strata_name ~ group_level,
        scales = "free_y",
        space = "free_y"
      ) +
      ggplot2::scale_y_discrete(
        limits = function(x) {
          intersect(c("England", "Northern Ireland", "Scotland", "Wales", 
                      "Q1(least deprived)", "Q2", "Q3", "Q4", "Q5(most deprived)",
                      "White", "Black", "Asian", "Unknown",
                      "Female", "Male", as.character(2:11),
                      "No", "Yes", "<=34", "35-44", "45-54", "55-64",
                      "65-74", "75-84", "85-94", ">=95", "Overall"), x) 
        },
        drop = TRUE
      ) +
      ggplot2::scale_x_continuous(
        breaks = scales::breaks_pretty(n = 4),
        labels = scales::label_percent(scale = 1)
      )+
      ggplot2::labs(x =NULL, y = "Number of vaccine booster recipients") +
      ggplot2::theme_minimal() +
      ggplot2::theme(panel.grid = element_blank(),
                     strip.text.x = ggplot2::element_text(
                       size = 16,
                       face = "bold"
                     ))
  })
  
  output$vaccinated_table_plot <- shiny::renderUI({
    x <- getVaccinatedTablePlot()
    renderInteractivePlot(x, input$vaccinated_table_plot_interactive)
  })
  
  output$vaccinated_tble_plot_download <- shiny::downloadHandler(
    filename = "plot_vaccinated.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getVaccinatedTablePlot(),
        width = as.numeric(input$vaccinated_table_plot_width),
        height = as.numeric(input$vaccinated_table_plot_height),
        units = input$vaccinated_table_plot_units,
        dpi = as.numeric(input$vaccinated_table_plot_dpi)
      )
    }
  )
  
  # summarise_table (Coverage)-----
  ## update message if filter is changed 

  shiny::observe({
    updateButtons$summarise_table <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_table_cdm_name,
      input$summarise_table_cohort_name,
      input$summarise_table_region,
      input$summarise_table_imd,
      input$summarise_table_sex,
      input$summarise_table_ethnicity,
      input$summarise_table_immunosuppressed,
      input$summarise_table_age_group,
      input$summarise_table_prior_dose,
      input$summarise_table_age_eligibility,
      input$summarise_table_overall,
      input$summarise_table_variable_name,
      input$summarise_table_estimate_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_table, {
    if (updateButtons$summarise_table == TRUE) {
      output$update_message_summarise_table <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_table <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_table, {
    updateButtons$summarise_table <- FALSE
  })
  ## get summarise_table data 
  
  getSummariseTableData <- shiny::eventReactive(input$update_summarise_table, {
    data[["summarise_table"]] |>
      print()|>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_table_cdm_name,
        .data$variable_name %in% input$summarise_table_variable_name,
        .data$estimate_name %in% input$summarise_table_estimate_name
      ) |>
      print()|>
      dplyr::mutate(
        group_level = pretty_labels(group_level, "group_level"),
        strata_level = pretty_labels(strata_level, "strata_level")
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_table_cohort_name) |>
      print()|>
      dplyr::filter(
        (.data$strata_name == "overall"          & .data$strata_level == "Overall") |
          (.data$strata_name == "region"           & .data$strata_level %in% input$summarise_table_region) |
          (.data$strata_name == "imd"              & .data$strata_level %in% input$summarise_table_imd) |
          (.data$strata_name == "sex"              & .data$strata_level %in% input$summarise_table_sex) |
          (.data$strata_name == "ethnicity"        & .data$strata_level %in% input$summarise_table_ethnicity) |
          (.data$strata_name == "prior_dose"       & .data$strata_level %in% input$summarise_table_prior_dose) |
          (.data$strata_name == "immunosuppressed" & .data$strata_level %in% input$summarise_table_immunosuppressed) |
          (.data$strata_name == "age_group"        & .data$strata_level %in% input$summarise_table_age_group) |
          (.data$strata_name == "age_eligibility"  & .data$strata_level %in% input$summarise_table_age_eligibility)
      ) 
      
  })
  getSummariseTableTidy <- shiny::reactive({
    tidyDT(getSummariseTableData(), input$summarise_table_tidy_columns, input$summarise_table_tidy_pivot_estimates)})
  output$summarise_table_tidy <- DT::renderDT({
    getSummariseTableTidy()
  })
  output$summarise_table_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseTableData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseTableTable <- shiny::reactive({
    getSummariseTableData() |>
      mutate(strata_name = case_when(.data$strata_name=="ethnicity" ~ "Ethnicity",
                                     .data$strata_name=="sex" ~ "Sex",
                                     .data$strata_name=="prior_dose" ~ "Prior dose",
                                     .data$strata_name=="imd" ~ "TDI",
                                     .data$strata_name=="age_eligibility" ~ "Age eligibility",
                                     .data$strata_name=="immunosuppressed" ~ "Immunosuppressed",
                                     .data$strata_name=="age_group" ~ "Age group",
                                     .data$strata_name=="overall" ~ "Overall",
                                     .data$strata_name=="region" ~ "Region",
                                     TRUE ~ strata_name)) |>
      simpleTable(
        header = input$summarise_table_table_header,
        group = input$summarise_table_table_group_column,
        hide = input$summarise_table_table_hide
      )
  })
  output$summarise_table_table <- gt::render_gt({
    getSummariseTableTable() 
  })
  
  output$summarise_table_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$summarise_table_table_format),
    content = function(file) {
      gt::gtsave(getSummariseTableTable(), file)
    }
  )
  # summarise_coverage (Coverage)-----
  ## update message if filter is changed
  
  shiny::observe({
    updateButtons$summarise_coverage <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_coverage_cdm_name,
      input$summarise_coverage_cohort_name,
      input$summarise_coverage_plot_strata_columns,
      ignoreInit = TRUE
    )
  
  shiny::observeEvent(updateButtons$summarise_coverage, {
    if (updateButtons$summarise_coverage == TRUE) {
      output$update_message_summarise_coverage <- shiny::renderUI(updateMessage)
    } else {
      output$update_message_summarise_coverage <- shiny::renderUI(NULL)
    }
  })
  
  shiny::observeEvent(input$update_summarise_coverage, {
    updateButtons$summarise_coverage <- FALSE
  })
  
  ## get summarise_table data
  plot_levels <- c("England", "Northern Ireland", "Scotland", "Wales", 
                   "Q1(least deprived)", "Q2", "Q3", "Q4", "Q5(most deprived)",
                   "White", "Black", "Asian", "Unknown",
                   "Female", "Male", as.character(2:11),
                   "No", "Yes", "<=34", "35-44", "45-54", "55-64",
                   "65-74", "75-84", "85-94", ">=95", "Overall")
  getSummariseCoverageTableData <- shiny::eventReactive(input$update_summarise_coverage, {
    data[["summarise_coverage"]] |>
      dplyr::filter(
        .data$variable_name == "vaccinated",
        .data$estimate_name == "percentage"
      ) |>
      
      dplyr::filter(
        .data$cdm_name %in% input$summarise_coverage_cdm_name) |>
      print()|>
      mutate(group_level = dplyr::recode(
        .data$group_level,
        a_2023 = "Autumn 2023",
        s_2024 = "Spring 2024",
        a_2024 = "Autumn 2024",
        s_2025 = "Spring 2025"
      ),
      strata_name = dplyr::recode(
        .data$strata_name,
        ethnicity = "Ethnicity",
        sex = "Sex",
        prior_dose = "Prior dose",
        imd = "TDI",
        age_eligibility = "Age eligibility",
        immunosuppressed = "Immunosuppressed",
        age_group = "Age group",
        overall = "Overall",
        region = "Region"))|>
      print()|>
      mutate(group_level = factor(
        .data$group_level,
        levels = c("Autumn 2023", "Spring 2024", "Autumn 2024", "Spring 2025")),
        #estimate_value = as.numeric(.data$estimate_value),
        strata_level = dplyr::recode(
          .data$strata_level, 
         Q1 = "Q1(least deprived)",
        Q5 = "Q5(most deprived)",
          `0` = "No",
          `1` = "Yes",
          missing = "Unknown",
          asian = "Asian",
          black = "Black",
          white = "White",
          overall = "Overall"))|>
      # mutate(
      #   strata_level = factor(
      #     .data$strata_level,
      #     levels = plot_levels
      #     )
      #   ) |>
      print()|>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_coverage_cohort_name) |>
      filter(.data$strata_name %in% input$summarise_coverage_plot_strata_columns) |>
      print()
  })

  
  ## get coverage plots
  getSummariseCoverageTablePlot <- shiny::reactive({
    
    df <- getSummariseCoverageTableData() |>
      print()|>
      #mutate(strata_level=if_else(is.na(.data$strata_level), "Overall", 
      #                                  .data$strata_level)) |>
      dplyr::mutate(estimate_value = as.numeric(.data$estimate_value)) |>
      dplyr::filter(!is.na(.data$estimate_value))
    
    ggplot2::ggplot(
      df,
      ggplot2::aes(x = .data$estimate_value, y = .data$strata_level, fill = .data$strata_name)
    ) +
      ggplot2::geom_col(show.legend = FALSE) +
      ggplot2::facet_grid(
        strata_name ~ group_level,
        scales = "free_y",
        space = "free_y"
      ) +
      ggplot2::scale_y_discrete(
        limits = function(x) {
          intersect(c("England", "Northern Ireland", "Scotland", "Wales", 
                      "Q1(least deprived)", "Q2", "Q3", "Q4", "Q5(most deprived)",
                      "White", "Black", "Asian", "Unknown",
                      "Female", "Male", as.character(2:11),
                      "No", "Yes", "<=34", "35-44", "45-54", "55-64",
                      "65-74", "75-84", "85-94", ">=95", "Overall"), x) 
        },
        drop = TRUE
      ) +
      ggplot2::scale_x_continuous(
        breaks = scales::breaks_pretty(n = 4),
        labels = scales::label_percent(scale = 1)
      )+
      ggplot2::labs(x =NULL, y = "Number of vaccine booster recipients") +
      ggplot2::theme_minimal() +
      ggplot2::theme(panel.grid = element_blank(),
                     strip.text.x = ggplot2::element_text(
                       size = 16,
                       face = "bold"
                     ))
  })

  output$summarise_coverage_plot <- shiny::renderUI({
    x <- getSummariseCoverageTablePlot()
    renderInteractivePlot(x, input$summarise_coverage_plot_interactive)
  })
  
  output$summarise_coverage_plot_download <- shiny::downloadHandler(
    filename = "plot_strata.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getVaccinatedTablePlot(),
        width = as.numeric(input$summarise_coverage_plot_width),
        height = as.numeric(input$summarise_coverage_plot_height),
        units = input$summarise_coverage_plot_units,
        dpi = as.numeric(input$summarise_coverage_plot_dpi)
      )
    }
  )
  # getSummariseCoveragePlot <- function(input_cohort_name) {
  #   shiny::reactive({
  #     
  #     strata_cols_selected <- input[[paste0("summarise_coverage_plot_strata_columns_", input_cohort_name)]]
  #     print(strata_cols_selected)
  #     strata_cols_not <- setdiff(
  #       c("region", "imd", "sex", "ethnicity", "overall", 
  #         "immunosuppressed", "prior_dose", "age_eligibility",
  #         "age_group"),
  #       strata_cols_selected
  #     )
  #     
  #     #shiny::req(length(strata_cols_selected) > 0)
  #     
  #     df <- getCoverageTableData()  |>
  #       
  #       dplyr::filter(
  #         .data$cdm_name %in% input$vaccinated_table_cdm_name ) |>
  #       mutate(group_level = dplyr::recode(
  #         group_level,
  #         a_2023 = "Autumn 2023",
  #         s_2024 = "Spring 2024",
  #         a_2024 = "Autumn 2024",
  #         s_2025 = "Spring 2025"
  #       ), 
  #       strata_name = dplyr::recode(
  #         strata_name,
  #         ethnicity = "Ethnicity",
  #         sex = "Sex",
  #         prior_dose = "Prior dose",
  #         imd = "IMD",
  #         age_eligibility = "Age eligibility",
  #         immunosuppressed = "Immunosuppressed",
  #         age_group = "Age group",
  #         overall = "Overall",
  #         region = "Region"),
  #       group_level = factor(
  #         group_level,
  #         levels = c("Autumn 2023", "Spring 2024", "Autumn 2024", "Spring 2025")
  #       )) |>
  #       
  #       omopgenerics::filterGroup(.data$cohort_name %in% input$vaccinated_table_cohort_name) 
  #   })
  #   
  #   plot_levels <- c("England", "Northern Ireland", "Scotland", "Wales", 
  #                    "Q1 (least deprived)", "Q2", "Q3", "Q4", "Q5 (most deprived)",
  #                    "White", "Black", "Asian", "Missing",
  #                    "Female", "Male", as.character(2:11),
  #                    "No", "Yes", "<=34", "35-44", "45-54", "55-64",
  #                    "65-74", "75-84", "85-94", ">=95", "Overall")
  #   
  #   getCoverageTablePlot <- shiny::reactive({
  #     strata_cols_selected <- input[["summarise_coverage_plot_strata_columns"]] 
  #     df <- getVaccinatedTableData() |>
  #       print()|>
  #       dplyr::filter(
  #         .data$variable_name == "vaccinated",
  #         .data$estimate_name == "percent"
  #       ) |>
  #       print()|>
  #       dplyr::mutate(
  #         estimate_value = as.numeric(estimate_value),
  #         strata_level = dplyr::recode(
  #           strata_level, 
  #           Q1 = "Q1 (least deprived)",
  #           Q5 = "Q5 (most deprived)",
  #           `0` = "No",
  #           `1` = "Yes",
  #           missing = "Missing",
  #           asian = "Asian",
  #           black = "Black",
  #           white = "White",
  #           overall = "Overall"),
  #         strata_level=factor(
  #           strata_level,
  #           levels = plot_levels,
  #           ordered = TRUE
  #         )
  #       ) |>
  #       #dplyr::filter(!is.na(.data$variable_name)) |>
  #       dplyr:: filter(.data$strata_name %in% strata_cols_selected) |>
  #       dplyr::filter(!is.na(.data$estimate_value))|>
  #       print()
  #     
  #     ggplot2::ggplot(
  #       df,
  #       ggplot2::aes(x = .data$estimate_value, y = .data$strata_level, fill = .data$strata_name)
  #     ) +
  #       ggplot2::geom_col(show.legend = FALSE) +
  #       ggplot2::facet_grid(
  #         strata_name ~ group_level,
  #         scales = "free_y",
  #         space = "free_y"
  #       ) +
  #       ggplot2::scale_y_discrete(
  #         limits = function(x) {
  #           intersect(plot_levels, x) 
  #         },
  #         drop = TRUE
  #       ) +
  #       ggplot2::scale_x_continuous(labels = scales::percent,
  #                                   breaks = scales::breaks_pretty(n = 4))+
  #       ggplot2::labs(x =NULL, y = "Number of vaccine booster recipients") +
  #       ggplot2::theme_minimal() +
  #       ggplot2::theme(panel.grid = element_blank(),
  #                      strip.text.x = ggplot2::element_text(
  #                        size = 16,
  #                        face = "bold"
  #                      )
  #                      # strip.text.y = ggplot2::element_text(
  #                      #   size = 14,
  #                      #   face = "bold"
  #                      #   )
  #       )
  #     #axis.text.x = ggplot2::element_text(angle = 45, hjust = 1)
  #   })
  # }
  # output$summarise_coverage_plot <- shiny::renderUI({
  #   x <- getCoverageTablePlot()
  #   renderInteractivePlot(x, input$summarise_coverage_plot_interactive)
  # })
  # 
  # output$vaccinated_table_plot_download <- shiny::downloadHandler(
  #   filename = "plot_coverage.png",
  #   content = function(file) {
  #     ggplot2::ggsave(
  #       filename = file,
  #       plot = getVaccinatedTablePlot(),
  #       width = as.numeric(input$summarise_coverage_plot_width),
  #       height = as.numeric(input$summarise_coverage_plot_height),
  #       units = input$summarise_coverage_plot_units,
  #       dpi = as.numeric(input$summarise_coverage_plot_dpi)
  #     )
  #   }
  # )
  # 
  # plot_a_2023 <- getSummariseCoveragePlot("a_2023")
  # plot_a_2023 <- getSummariseCoveragePlot("a_2023")
  # plot_s_2024 <- getSummariseCoveragePlot("s_2024")
  # plot_a_2024 <- getSummariseCoveragePlot("a_2024")
  # plot_s_2025 <- getSummariseCoveragePlot("s_2025")
  # 
  # output$summarise_coverage_plot_a_2023 <- shiny::renderUI({
  #   x <- plot_a_2023()
  #   renderInteractivePlot(x, input$summarise_coverage_plot_interactive_a_2023)
  # })
  # 
  # output$summarise_coverage_plot_s_2024 <- shiny::renderUI({
  #   x <- plot_s_2024()
  #   renderInteractivePlot(x, input$summarise_coverage_plot_interactive_s_2024)
  # })
  # 
  # output$summarise_coverage_plot_a_2024 <- shiny::renderUI({
  #   x <- plot_a_2024()
  #   renderInteractivePlot(x, input$summarise_coverage_plot_interactive_a_2024)
  # })
  # 
  # output$summarise_coverage_plot_s_2025 <- shiny::renderUI({
  #   x <- plot_s_2025()
  #   renderInteractivePlot(x, input$summarise_coverage_plot_interactive_s_2025)
  # })
  # 
  # output$summarise_coverage_plot_download_a_2023 <- shiny::downloadHandler(
  #   filename = "plot_coverage_a_2023.png",
  #   content = function(file) {
  #     ggplot2::ggsave(
  #       filename = file,
  #       plot = plot_a_2023(),
  #       width = as.numeric(input$summarise_coverage_plot_width_a_2023),
  #       height = as.numeric(input$summarise_coverage_plot_height_a_2023),
  #       units = input$summarise_coverage_plot_units_a_2023,
  #       dpi = as.numeric(input$summarise_coverage_plot_dpi_a_2023)
  #     )
  #   }
  # )
  # 
  # output$summarise_coverage_plot_download_s_2024 <- shiny::downloadHandler(
  #   filename = "plot_coverage_s_2024.png",
  #   content = function(file) {
  #     ggplot2::ggsave(
  #       filename = file,
  #       plot = plot_s_2024(),
  #       width = as.numeric(input$summarise_coverage_plot_width_s_2024),
  #       height = as.numeric(input$summarise_coverage_plot_height_s_2024),
  #       units = input$summarise_coverage_plot_units_s_2024,
  #       dpi = as.numeric(input$summarise_coverage_plot_dpi_s_2024)
  #     )
  #   }
  # )
  # 
  # output$summarise_coverage_plot_download_a_2024 <- shiny::downloadHandler(
  #   filename = "plot_coverage_a_2024.png",
  #   content = function(file) {
  #     ggplot2::ggsave(
  #       filename = file,
  #       plot = plot_a_2024(),
  #       width = as.numeric(input$summarise_coverage_plot_width_a_2024),
  #       height = as.numeric(input$summarise_coverage_plot_height_a_2024),
  #       units = input$summarise_coverage_plot_units_a_2024,
  #       dpi = as.numeric(input$summarise_coverage_plot_dpi_a_2024)
  #     )
  #   }
  # )
  # 
  # output$summarise_coverage_plot_download_s_2025 <- shiny::downloadHandler(
  #   filename = "plot_coverage_s_2025.png",
  #   content = function(file) {
  #     ggplot2::ggsave(
  #       filename = file,
  #       plot = plot_s_2025(),
  #       width = as.numeric(input$summarise_coverage_plot_width_s_2025),
  #       height = as.numeric(input$summarise_coverage_plot_height_s_2025),
  #       units = input$summarise_coverage_plot_units_s_2025,
  #       dpi = as.numeric(input$summarise_coverage_plot_dpi_s_2025)
  #     )
  #   }
  # )
  # summarise_log_file -----
  ## update message if filter is changed
  shiny::observe({
    updateButtons$summarise_log_file <- TRUE
  }) |>
    shiny::bindEvent(
      input$summarise_log_file_cdm_name,
      input$summarise_log_file_variable_name,
      ignoreInit = TRUE
    )
  shiny::observeEvent(updateButtons$summarise_log_file, {
    if (updateButtons$summarise_log_file == TRUE) {
      output$update_message_summarise_log_file <- shiny::renderUI(updateMessage) # defined in functions.R
    } else {
      output$update_message_summarise_log_file <- shiny::renderUI(NULL)
    }
  })
  shiny::observeEvent(input$update_summarise_log_file, {
    updateButtons$summarise_log_file <- FALSE
  })
  
  # Linear plots -----
  ## Linear plots imported by me 
  output$linear_regression <- shiny::renderUI({
    if (isTRUE(input$models_combined)) {
      img <- "lr_all.png"
    } else {
      img <- "lr_sep.png"
    }
    shiny::tags$img(src = img, width = "80%")
  })
  
  output$summarise_linerplot_plot_download <- shiny::downloadHandler(
    filename = function() {
      if (isTRUE(input$models_combined)) {
        "linear_regression_combined.png"
      } else {
        "linear_regression_sequential.png"
      }
    },
    content = function(file) {
      if (isTRUE(input$models_combined)) {
        file.copy("www/lr_all.png", file)
      } else {
        file.copy("www/lr_sep.png", file)
      }
    }
  )
  
  ## get summarise_log_file data
  getSummariseLogFileData <- shiny::eventReactive(input$update_summarise_log_file, {
    data[["summarise_log_file"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_log_file_cdm_name,
        .data$variable_name %in% input$summarise_log_file_variable_name
      )
  })
  getSummariseLogFileTable <- shiny::reactive({
    getSummariseLogFileData() |>
      dplyr::filter(.data$estimate_name == "date_time") |>
      visOmopResults::visOmopTable(
        header = "cdm_name",
        hide = c("variable_level", "estimate_name")
      )
  })
  output$summarise_log_file_table <- gt::render_gt({
    getSummariseLogFileTable()
  })
  output$summarise_log_file_table_download <- shiny::downloadHandler(
    filename = paste0("table_log.", input$summarise_log_file_table_format),
    content = function(file) {
      gt::gtsave(getSummariseLogFileTable(), file)
    }
  )
  getSummariseLogFilePlot <- shiny::reactive({
    getSummariseLogFileData() |>
      dplyr::filter(.data$estimate_name == "elapsed_time") |>
      visOmopResults::barPlot(
        x = c("log_id", "variable_name"),
        y = "elapsed_time",
        colour = "cdm_name",
        position = input$summarise_log_file_plot_position
      )
  })
  output$summarise_log_file_plot <- shiny::renderUI({
    x <- getSummariseLogFilePlot()
    renderInteractivePlot(x, input$summarise_log_file_plot_interactive)
  })
  output$summarise_log_file_plot_download <- shiny::downloadHandler(
    filename = "plot_logs.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getSummariseLogFilePlot(),
        width = as.numeric(input$summarise_log_file_plot_width),
        height = as.numeric(input$summarise_log_file_plot_height),
        units = input$summarise_log_file_plot_units,
        dpi = as.numeric(input$summarise_log_file_plot_dpi)
      )
    })
  
  # objective 3: associated factors ----
  
  models <- c(
    "fit_agr", "fit_agr_sex", "fit_agr_sex_eth", "fit_agr_sex_imd",
    "fit_agr_sex_reg", "fit_agr_sex_immuno", "fit_all"
  )
  
  plot_levels <- c(
    "Non immunosuppressed", "Immunosuppressed",
    "England", "Northern Ireland", "Scotland", "Wales",
    "Q1", "Q2", "Q3", "Q4", "Q5",
    "White", "Black", "Asian", "Missing",
    "Female", "Male",
    "<=34", "35-44", "45-54", "55-64",
    "65-74", "75-84", "85-94", ">=95"
  )
  
  var_labels <- c(
    age_group = "Age group",
    sex = "Sex",
    ethnicity = "Ethnicity",
    imd = "TDI",
    region = "Region",
    immuno = "Immunosuppression"
  )
  
  var_prefixes <- names(var_labels)
  
  make_ref_plot <- function(campaign_levels) {
    tidyr::crossing(
      tibble::tibble(
        term = c("75-84", "Female", "White", "Q3", "Scotland", "Non immunosuppressed"),
        estimate = c(1, 1, 1, 1, 1, 1),
        var_group = unname(var_labels)
      ),
      campaign = campaign_levels
    ) |>
      dplyr::mutate(
        term = factor(term, levels = plot_levels),
        var_group = factor(var_group, levels = unname(var_labels))
      )
  }
  
  getLinearRegressionData <- shiny::reactive({
    tidy_fit |>
      dplyr::filter(.data$term != "(Intercept)") |>
      dplyr::mutate(
        var_group = purrr::map_chr(.data$term, ~ {
          match <- var_prefixes[stringr::str_starts(.x, .env$var_prefixes)]
          if (length(match) == 0) NA_character_ else match[1]
        }),
        term = dplyr::if_else(
          .data$var_group != "immuno",
          stringr::str_remove(.data$term, paste0("^", .data$var_group)),
          "Immunosuppressed"
        ),
        term = dplyr::if_else(
          .data$var_group == "ethnicity",
          stringr::str_to_title(.data$term),
          .data$term
        ),
        term = factor(.data$term, levels = plot_levels),
        campaign = dplyr::case_when(
          campaign == "a_2023" ~ "Autumn 2023",
          campaign == "a_2024" ~ "Autumn 2024",
          campaign == "s_2024" ~ "Spring 2024",
          campaign == "s_2025" ~ "Spring 2025",
          TRUE ~ campaign
        ),
        campaign = factor(
          .data$campaign,
          levels = c("Autumn 2023", "Spring 2024", "Autumn 2024", "Spring 2025")
        ),
        var_group = factor(
          .data$var_group,
          levels = names(var_labels),
          labels = unname(var_labels)
        )
      ) |>
      dplyr::filter(
        (.data$model == models[[1]] & .data$var_group == unname(var_labels)[[1]]) |
          (.data$model == models[[2]] & .data$var_group == unname(var_labels)[[2]]) |
          (.data$model == models[[3]] & .data$var_group == unname(var_labels)[[3]]) |
          (.data$model == models[[4]] & .data$var_group == unname(var_labels)[[4]]) |
          (.data$model == models[[5]] & .data$var_group == unname(var_labels)[[5]]) |
          (.data$model == models[[6]] & .data$var_group == unname(var_labels)[[6]]) |
          (.data$model == models[[7]])
      )
  })
  
  getLinearRegressionPlot <- shiny::reactive({
    df <- getLinearRegressionData()
    
    ref_plot <- make_ref_plot(unique(df$campaign))
    
    if (isTRUE(input$models_combined)) {
      ggplot2::ggplot(
        df |> dplyr::filter(.data$model == "fit_all"),
        ggplot2::aes(x = estimate, y = term, colour = var_group)
      ) +
        ggplot2::geom_point() +
        ggplot2::geom_errorbar(
          ggplot2::aes(xmin = conf.low, xmax = conf.high),
          orientation = "y",
          width = 0.2
        ) +
        ggplot2::geom_point(
          data = ref_plot,
          ggplot2::aes(x = estimate, y = term, colour = var_group),
          shape = 0,
          show.legend = FALSE
        ) +
        ggplot2::facet_grid(~ campaign) +
        ggplot2::geom_vline(xintercept = 1, linetype = "dashed") +
        ggplot2::scale_x_continuous(
          trans = "log",
          limits = c(0.05, 2),
          breaks = c(0.05, 0.1, 0.25, 0.5, 1, 2)
        ) +
        ggplot2::scale_y_discrete(limits = plot_levels) +
        ggplot2::scale_colour_manual(
          values = c(
            `Age group` = "#FF0000",
            Sex = "#0000CC",
            Ethnicity = "deeppink2",
            Region = "darkorange1",
            TDI = "#009900",
            Immunosuppression = "magenta4"
            
          ),
          name = "Covariates: "
        ) +
        ggplot2::guides(
          colour = ggplot2::guide_legend(override.aes = list(shape = 16))
        ) +
        ggplot2::labs(
          x = "Odds Ratio (log scale)",
          y = ""
        ) +
        ggplot2::theme_bw() +
        ggplot2::theme(
          axis.title = element_text(size = 16),
          axis.text = element_text(size = 14),
          legend.title = element_text(size = 16),
          legend.text = element_text(size = 14),
          strip.text = element_text(size = 14),
          axis.text.x = element_text(angle = 45, hjust = 1)
        )
    } else {
      ggplot2::ggplot(
        df |> dplyr::filter(.data$model != "fit_all"),
        ggplot2::aes(x = estimate, y = term, colour = var_group)
      ) +
        ggplot2::geom_point() +
        ggplot2::geom_errorbarh(
          ggplot2::aes(xmin = conf.low, xmax = conf.high),
          height = 0.2
        ) +
        ggplot2::geom_point(
          data = ref_plot,
          ggplot2::aes(x = estimate, y = term, colour = var_group),
          shape = 0,
          show.legend = FALSE
        ) +
        ggplot2::geom_vline(xintercept = 1, linetype = "dashed") +
        ggplot2::scale_y_discrete(
          limits = function(x) intersect(plot_levels, x),
          drop = TRUE
        ) +
        ggplot2::facet_grid(
          var_group ~ campaign,
          scales = "free_y",
          space = "free_y",
          labeller = ggplot2::labeller(
            var_group = c(Immunosuppression = "I*")
          )
        ) +
        ggplot2::scale_x_continuous(
          trans = "log",
          limits = c(0.05, 2),
          breaks = c(0.05, 0.1, 0.25, 0.5, 1, 2)
        ) +
        ggplot2::scale_colour_manual(
          values = c(
            `Age group` = "#FF0000",
            Sex = "#0000CC",
            Ethnicity = "deeppink2",
            Region = "darkorange1",
            TDI = "#009900",
            Immunosuppression = "magenta4"
            
          ),
          labels = c(
            "Age group", "Sex", "Ethnicity",
            "Region", "TDI", "I*: Immunosupression"
          ),
          name = "Covariates: "
        ) +
        ggplot2::guides(
          colour = ggplot2::guide_legend(override.aes = list(shape = 16))
        ) +
        ggplot2::labs(
          x = "Odds Ratio (log scale)",
          y = "",
          colour = "Variable"
        ) +
        ggplot2::theme_bw() +
        ggplot2::theme(
          axis.title = element_text(size = 16),
          axis.text = element_text(size = 14),
          legend.title = element_text(size = 16),
          legend.text = element_text(size = 14),
          strip.text = element_text(size = 14),
          axis.text.x = element_text(angle = 45, hjust = 1)
        )
    }
  })
  
  output$linear_regression <- shiny::renderUI({
    x <- getLinearRegressionPlot()
    renderInteractivePlot(x, input$linear_regression_interactive)
  })
  
  output$summarise_linerplot_plot_download <- shiny::downloadHandler(
    filename = "linear_regression.png",
    content = function(file) {
      ggplot2::ggsave(
        filename = file,
        plot = getLinearRegressionPlot(),
        width = 16,
        height = 9,
        units = "cm",
        dpi = 300
      )
    }
  )
}